### ISSUE TITLE
Config `ui.border` not being respected by picker window

### ISSUE THREAD

**Issue by willothy** [neph-iap/easycolor.nvim#2]
https://github.com/neph-iap/easycolor.nvim/blob/ba934b2ec06b02b2a98cb6f62ce76cc29acb8f6f/lua/easycolor/ui/init.lua#L273

**Comment by neph-iap** [comment]
Fixed in [942e5d8](https://github.com/neph-iap/easycolor.nvim/commit/942e5d86374e5ed69b57e913470f2168de4aa726)

**Comment by willothy** [comment]
> Fixed in [942e5d8](https://github.com/neph-iap/easycolor.nvim/commit/942e5d86374e5ed69b57e913470f2168de4aa726)

Awesome, thanks!
